# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "brisby"
BBFILE_PATTERN_brisby = "^${LAYERDIR}/"
BBFILE_PRIORITY_brisby = "10"

LAYERDEPENDS_brisby = "balena-common"
LAYERSERIES_COMPAT_brisby = "dunfell kirkstone"
